//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVIService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInternational", Namespace="http://www.serviceobjects.com")]
    public partial class ContactInternational : object
    {
        
        private string OverallCertaintyField;
        
        private string OverallQualityField;
        
        private string LeadTypeField;
        
        private string LeadCountryField;
        
        private string NoteCodesField;
        
        private string NoteDescField;
        
        private string NameCertaintyField;
        
        private string NameQualityField;
        
        private string FirstNameLatinField;
        
        private string LastNameLatinField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string NameNoteCodesField;
        
        private string NameNoteDescField;
        
        private string AddressCertaintyField;
        
        private string AddressQualityField;
        
        private string AddressResolutionLevelField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string AddressLine3Field;
        
        private string AddressLine4Field;
        
        private string AddressLine5Field;
        
        private string AddressLocalityField;
        
        private string AddressAdminAreaField;
        
        private string AddressPostalCodeField;
        
        private string AddressCountryField;
        
        private string AddressNoteCodesField;
        
        private string AddressNoteDescField;
        
        private string EmailCertaintyField;
        
        private string EmailQualityField;
        
        private string EmailCorrectedField;
        
        private string EmailNoteCodesField;
        
        private string EmailNoteDescField;
        
        private string IPCertaintyField;
        
        private string IPQualityField;
        
        private string IPLocalityField;
        
        private string IPAdminAreaField;
        
        private string IPCountryField;
        
        private string IPNoteCodesField;
        
        private string IPNoteDescField;
        
        private string Phone1CertaintyField;
        
        private string Phone1QualityField;
        
        private string Phone1LocalityField;
        
        private string Phone1AdminAreaField;
        
        private string Phone1CountryField;
        
        private string Phone1NoteCodesField;
        
        private string Phone1NoteDescField;
        
        private string Phone2CertaintyField;
        
        private string Phone2QualityField;
        
        private string Phone2LocalityField;
        
        private string Phone2AdminAreaField;
        
        private string Phone2CountryField;
        
        private string Phone2NoteCodesField;
        
        private string Phone2NoteDescField;
        
        private LVIService.PhoneContact PhoneContactField;
        
        private string BusinessCertaintyField;
        
        private string BusinessQualityField;
        
        private string BusinessNameField;
        
        private string BusinessDomainField;
        
        private string BusinessEmailField;
        
        private string BusinessNoteCodesField;
        
        private string BusinessNoteDescField;
        
        private LVIService.InformationComponent[] InformationComponentsField;
        
        private LVIService.Error ErrorField;
        
        private string DEBUGField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OverallCertainty
        {
            get
            {
                return this.OverallCertaintyField;
            }
            set
            {
                this.OverallCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OverallQuality
        {
            get
            {
                return this.OverallQualityField;
            }
            set
            {
                this.OverallQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LeadType
        {
            get
            {
                return this.LeadTypeField;
            }
            set
            {
                this.LeadTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LeadCountry
        {
            get
            {
                return this.LeadCountryField;
            }
            set
            {
                this.LeadCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NoteCodes
        {
            get
            {
                return this.NoteCodesField;
            }
            set
            {
                this.NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NoteDesc
        {
            get
            {
                return this.NoteDescField;
            }
            set
            {
                this.NoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NameCertainty
        {
            get
            {
                return this.NameCertaintyField;
            }
            set
            {
                this.NameCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NameQuality
        {
            get
            {
                return this.NameQualityField;
            }
            set
            {
                this.NameQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FirstNameLatin
        {
            get
            {
                return this.FirstNameLatinField;
            }
            set
            {
                this.FirstNameLatinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LastNameLatin
        {
            get
            {
                return this.LastNameLatinField;
            }
            set
            {
                this.LastNameLatinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string NameNoteCodes
        {
            get
            {
                return this.NameNoteCodesField;
            }
            set
            {
                this.NameNoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NameNoteDesc
        {
            get
            {
                return this.NameNoteDescField;
            }
            set
            {
                this.NameNoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string AddressCertainty
        {
            get
            {
                return this.AddressCertaintyField;
            }
            set
            {
                this.AddressCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string AddressQuality
        {
            get
            {
                return this.AddressQualityField;
            }
            set
            {
                this.AddressQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string AddressResolutionLevel
        {
            get
            {
                return this.AddressResolutionLevelField;
            }
            set
            {
                this.AddressResolutionLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string AddressLine3
        {
            get
            {
                return this.AddressLine3Field;
            }
            set
            {
                this.AddressLine3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string AddressLine4
        {
            get
            {
                return this.AddressLine4Field;
            }
            set
            {
                this.AddressLine4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string AddressLine5
        {
            get
            {
                return this.AddressLine5Field;
            }
            set
            {
                this.AddressLine5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string AddressLocality
        {
            get
            {
                return this.AddressLocalityField;
            }
            set
            {
                this.AddressLocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string AddressAdminArea
        {
            get
            {
                return this.AddressAdminAreaField;
            }
            set
            {
                this.AddressAdminAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string AddressPostalCode
        {
            get
            {
                return this.AddressPostalCodeField;
            }
            set
            {
                this.AddressPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string AddressCountry
        {
            get
            {
                return this.AddressCountryField;
            }
            set
            {
                this.AddressCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string AddressNoteCodes
        {
            get
            {
                return this.AddressNoteCodesField;
            }
            set
            {
                this.AddressNoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string AddressNoteDesc
        {
            get
            {
                return this.AddressNoteDescField;
            }
            set
            {
                this.AddressNoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string EmailCertainty
        {
            get
            {
                return this.EmailCertaintyField;
            }
            set
            {
                this.EmailCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string EmailQuality
        {
            get
            {
                return this.EmailQualityField;
            }
            set
            {
                this.EmailQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string EmailCorrected
        {
            get
            {
                return this.EmailCorrectedField;
            }
            set
            {
                this.EmailCorrectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string EmailNoteCodes
        {
            get
            {
                return this.EmailNoteCodesField;
            }
            set
            {
                this.EmailNoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string EmailNoteDesc
        {
            get
            {
                return this.EmailNoteDescField;
            }
            set
            {
                this.EmailNoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string IPCertainty
        {
            get
            {
                return this.IPCertaintyField;
            }
            set
            {
                this.IPCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string IPQuality
        {
            get
            {
                return this.IPQualityField;
            }
            set
            {
                this.IPQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string IPLocality
        {
            get
            {
                return this.IPLocalityField;
            }
            set
            {
                this.IPLocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string IPAdminArea
        {
            get
            {
                return this.IPAdminAreaField;
            }
            set
            {
                this.IPAdminAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string IPCountry
        {
            get
            {
                return this.IPCountryField;
            }
            set
            {
                this.IPCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string IPNoteCodes
        {
            get
            {
                return this.IPNoteCodesField;
            }
            set
            {
                this.IPNoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string IPNoteDesc
        {
            get
            {
                return this.IPNoteDescField;
            }
            set
            {
                this.IPNoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Phone1Certainty
        {
            get
            {
                return this.Phone1CertaintyField;
            }
            set
            {
                this.Phone1CertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string Phone1Quality
        {
            get
            {
                return this.Phone1QualityField;
            }
            set
            {
                this.Phone1QualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string Phone1Locality
        {
            get
            {
                return this.Phone1LocalityField;
            }
            set
            {
                this.Phone1LocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string Phone1AdminArea
        {
            get
            {
                return this.Phone1AdminAreaField;
            }
            set
            {
                this.Phone1AdminAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string Phone1Country
        {
            get
            {
                return this.Phone1CountryField;
            }
            set
            {
                this.Phone1CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string Phone1NoteCodes
        {
            get
            {
                return this.Phone1NoteCodesField;
            }
            set
            {
                this.Phone1NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string Phone1NoteDesc
        {
            get
            {
                return this.Phone1NoteDescField;
            }
            set
            {
                this.Phone1NoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string Phone2Certainty
        {
            get
            {
                return this.Phone2CertaintyField;
            }
            set
            {
                this.Phone2CertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string Phone2Quality
        {
            get
            {
                return this.Phone2QualityField;
            }
            set
            {
                this.Phone2QualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string Phone2Locality
        {
            get
            {
                return this.Phone2LocalityField;
            }
            set
            {
                this.Phone2LocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string Phone2AdminArea
        {
            get
            {
                return this.Phone2AdminAreaField;
            }
            set
            {
                this.Phone2AdminAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string Phone2Country
        {
            get
            {
                return this.Phone2CountryField;
            }
            set
            {
                this.Phone2CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string Phone2NoteCodes
        {
            get
            {
                return this.Phone2NoteCodesField;
            }
            set
            {
                this.Phone2NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string Phone2NoteDesc
        {
            get
            {
                return this.Phone2NoteDescField;
            }
            set
            {
                this.Phone2NoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public LVIService.PhoneContact PhoneContact
        {
            get
            {
                return this.PhoneContactField;
            }
            set
            {
                this.PhoneContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string BusinessCertainty
        {
            get
            {
                return this.BusinessCertaintyField;
            }
            set
            {
                this.BusinessCertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string BusinessQuality
        {
            get
            {
                return this.BusinessQualityField;
            }
            set
            {
                this.BusinessQualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string BusinessName
        {
            get
            {
                return this.BusinessNameField;
            }
            set
            {
                this.BusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=58)]
        public string BusinessDomain
        {
            get
            {
                return this.BusinessDomainField;
            }
            set
            {
                this.BusinessDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string BusinessEmail
        {
            get
            {
                return this.BusinessEmailField;
            }
            set
            {
                this.BusinessEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string BusinessNoteCodes
        {
            get
            {
                return this.BusinessNoteCodesField;
            }
            set
            {
                this.BusinessNoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public string BusinessNoteDesc
        {
            get
            {
                return this.BusinessNoteDescField;
            }
            set
            {
                this.BusinessNoteDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public LVIService.InformationComponent[] InformationComponents
        {
            get
            {
                return this.InformationComponentsField;
            }
            set
            {
                this.InformationComponentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public LVIService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string DEBUG
        {
            get
            {
                return this.DEBUGField;
            }
            set
            {
                this.DEBUGField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneContact", Namespace="http://www.serviceobjects.com")]
    public partial class PhoneContact : object
    {
        
        private string NameField;
        
        private string AddressField;
        
        private string CityField;
        
        private string StateField;
        
        private string ZipField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.serviceobjects.com")]
    public partial class Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationComponent", Namespace="http://www.serviceobjects.com")]
    public partial class InformationComponent : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="LVIService.ILVISoapService")]
    public interface ILVISoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/ILVISoapService/ValidateLeadInternational", ReplyAction="http://www.serviceobjects.com/ILVISoapService/ValidateLeadInternationalResponse")]
        System.Threading.Tasks.Task<LVIService.ContactInternational> ValidateLeadInternationalAsync(
                    string FullName, 
                    string Salutation, 
                    string FirstName, 
                    string LastName, 
                    string BusinessName, 
                    string BusinessDomain, 
                    string BusinessEIN, 
                    string Address1, 
                    string Address2, 
                    string Address3, 
                    string Address4, 
                    string Address5, 
                    string Locality, 
                    string AdminArea, 
                    string PostalCode, 
                    string Country, 
                    string Phone1, 
                    string Phone2, 
                    string Email, 
                    string IPAddress, 
                    string Gender, 
                    string DateOfBirth, 
                    string UTCCaptureTime, 
                    string OutputLanguage, 
                    string TestType, 
                    string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ILVISoapServiceChannel : LVIService.ILVISoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LVISoapServiceClient : System.ServiceModel.ClientBase<LVIService.ILVISoapService>, LVIService.ILVISoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LVISoapServiceClient() : 
                base(LVISoapServiceClient.GetDefaultBinding(), LVISoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOTSLeadValidationInternational.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LVISoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LVISoapServiceClient.GetBindingForEndpoint(endpointConfiguration), LVISoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LVISoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LVISoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LVISoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LVISoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LVISoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LVIService.ContactInternational> ValidateLeadInternationalAsync(
                    string FullName, 
                    string Salutation, 
                    string FirstName, 
                    string LastName, 
                    string BusinessName, 
                    string BusinessDomain, 
                    string BusinessEIN, 
                    string Address1, 
                    string Address2, 
                    string Address3, 
                    string Address4, 
                    string Address5, 
                    string Locality, 
                    string AdminArea, 
                    string PostalCode, 
                    string Country, 
                    string Phone1, 
                    string Phone2, 
                    string Email, 
                    string IPAddress, 
                    string Gender, 
                    string DateOfBirth, 
                    string UTCCaptureTime, 
                    string OutputLanguage, 
                    string TestType, 
                    string LicenseKey)
        {
            return base.Channel.ValidateLeadInternationalAsync(FullName, Salutation, FirstName, LastName, BusinessName, BusinessDomain, BusinessEIN, Address1, Address2, Address3, Address4, Address5, Locality, AdminArea, PostalCode, Country, Phone1, Phone2, Email, IPAddress, Gender, DateOfBirth, UTCCaptureTime, OutputLanguage, TestType, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSLeadValidationInternational))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSLeadValidationInternational))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/LVI/soap.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LVISoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.DOTSLeadValidationInternational);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LVISoapServiceClient.GetEndpointAddress(EndpointConfiguration.DOTSLeadValidationInternational);
        }
        
        public enum EndpointConfiguration
        {
            
            DOTSLeadValidationInternational,
        }
    }
}
